# Generated by Django 6.0.1 on 2026-01-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_fooditemimage_food_item'),
    ]

    operations = [
    ]
