# Generated by Django 6.0.1 on 2026-01-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_add_is_special_to_FoodItem'),
    ]

    operations = [
    ]
