# Generated by Django 6.0.1 on 2026-01-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_add_is_special_to_FoodItem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_special',
            field=models.BooleanField(default=True),
        ),
    ]
