# Generated by Django 6.0.1 on 2026-02-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_fooditem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('recipient_type', models.CharField(choices=[('customer', 'Customer'), ('delivery_person', 'Delivery Person')], max_length=20)),
                ('send_datetime', models.DateTimeField()),
                ('read_status', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
