# Generated by Django 6.0.1 on 2026-02-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
