# Generated by Django 6.0.1 on 2026-02-10 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_notification_send_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='has_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FoodItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='adminpanel.fooditem')),
            ],
        ),
    ]
