# Generated by Django 6.0.1 on 2026-02-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_fooditem_has_variant_fooditemvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditemvariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
