# Generated by Django 6.0.2 on 2026-02-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_fooditemvariant_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='preparation_time',
            field=models.IntegerField(default=20),
        ),
    ]
