# Generated by Django 6.0.2 on 2026-03-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_fooditem_description'),
        ('adminpanel', '0012_fooditem_preparation_time'),
    ]

    operations = [
    ]
