# Generated by Django 6.0.2 on 2026-02-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_area_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='delivery_time',
            field=models.IntegerField(default=15),
        ),
    ]
