# Generated by Django 6.0.2 on 2026-03-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_area_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
        ),
    ]
