# Generated by Django 6.0.2 on 2026-03-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_area_delivery_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='delivery_charge',
        ),
    ]
