# Generated by Django 6.0.1 on 2026-02-12 03:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_fooditem_has_variant_fooditemvariant'),
        ('orders', '0002_cart_variant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'food_item', 'variant')},
        ),
    ]
