# Generated by Django 6.0.1 on 2026-02-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
