# Generated by Django 6.0.1 on 2026-02-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_feedbackrating'),
        ('orders', '0004_cart_original_price'),
    ]

    operations = [
    ]
