# Generated by Django 6.0.1 on 2026-02-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_complaint_complaintresolution_returnorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_full_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_proofs/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='returned_items',
            field=models.ManyToManyField(blank=True, to='orders.orderdetail'),
        ),
    ]
