# Generated by Django 6.0.1 on 2026-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_complaint_is_full_return_complaint_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
