# Generated by Django 6.0.1 on 2026-01-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchasedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('production_date', models.DateField()),
                ('quantity_produced', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_used', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.ingredient')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.prepareditem')),
            ],
        ),
    ]
