# Generated by Django 6.0.1 on 2026-02-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchase_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='available_qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredientusage',
            name='qty_used',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
