# Generated by Django 6.0.1 on 2026-02-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_alter_ingredient_available_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='available_qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredientusage',
            name='qty_used',
            field=models.IntegerField(),
        ),
    ]
