# Generated by Django 6.0.1 on 2026-02-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_alter_ingredient_available_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientusage',
            name='qty_used',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
