# Generated by Django 6.0.2 on 2026-02-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_alter_ingredientusage_qty_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepareditem',
            name='preparation_time',
            field=models.IntegerField(default=20),
        ),
    ]
