# Generated by Django 6.0.2 on 2026-02-28 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_prepareditem_preparation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepareditem',
            name='preparation_time',
        ),
    ]
