# Generated by Django 6.0.1 on 2026-02-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverypanel', '0002_assignorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignorder',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DELIVERED', 'Delivered')], default='REQUESTED', max_length=25),
        ),
    ]
